defaults:
  - _self_
  - model: vit_tiny
  - dataset: dummy

weights_dir: "weights"
model_compile: true

trainer:
  max_epochs: 50
  precision: "bf16-mixed"
  accelerator: "gpu"
  devices: 1
  strategy: "ddp_find_unused_parameters_false"
  gradient_clip_val: 1.0
  log_every_n_steps: 10
  benchmark: true

logger:
  project: "mvreid"
  name: null
  offline: false
